### PR TITLE
Fix filename

### PR DESCRIPTION
**Pull request by warwickmm**
This removes a leading underscore from a filename:

`_20180306__tx__primary__haskell__precinct.csv -> 20180306__tx__primary__haskell__precinct.csv`

### CODE REVIEW

**Comment by dwillis** [comment]
@warwickmm yeah, this one has an underscore because it's based on unofficial results (we haven't been able to get official results) and I didn't want to imply otherwise. Although an underscore is not a great way to do it.

**Comment by warwickmm** [comment]
Ah, no problem.  I made a similar change in pull request #347.  Should I revert that one as well?

**Comment by warwickmm** [comment]
From what I can tell, there are (were) only two such files:

```
_20180306__tx__primary__haskell__precinct.csv
_20180306__tx__primary__stonewall__precinct.csv (renamed in #347)
```

**Comment by dwillis** [comment]
@warwickmm yeah, sorry, should have caught that.

**Comment by warwickmm** [comment]
No problem at all.  Pull request #358 reverts the filename change made in #347.

**Pull request closed without merging**
